// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFjp432-U_6YAccXdUXjgJjW165UGyDLY',
    appId: '1:971580789222:web:6ede2d60c9b9bd4edf0627',
    messagingSenderId: '971580789222',
    projectId: 'my-napo-pizza',
    authDomain: 'my-napo-pizza.firebaseapp.com',
    storageBucket: 'my-napo-pizza.appspot.com',
    measurementId: 'G-YDBJM7KXHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmA_3osegQ9bfQG4G6dp6fLEaI44CbiEg',
    appId: '1:971580789222:android:a3ecc756d1a90fb0df0627',
    messagingSenderId: '971580789222',
    projectId: 'my-napo-pizza',
    storageBucket: 'my-napo-pizza.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQYFcUX_liuCtpkndr_8GFK7f7W-v0LM8',
    appId: '1:971580789222:ios:2af1b7cdb8bd08c2df0627',
    messagingSenderId: '971580789222',
    projectId: 'my-napo-pizza',
    storageBucket: 'my-napo-pizza.appspot.com',
    iosBundleId: 'com.example.mynapopizza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQYFcUX_liuCtpkndr_8GFK7f7W-v0LM8',
    appId: '1:971580789222:ios:2af1b7cdb8bd08c2df0627',
    messagingSenderId: '971580789222',
    projectId: 'my-napo-pizza',
    storageBucket: 'my-napo-pizza.appspot.com',
    iosBundleId: 'com.example.mynapopizza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFjp432-U_6YAccXdUXjgJjW165UGyDLY',
    appId: '1:971580789222:web:42cf40839328dbcadf0627',
    messagingSenderId: '971580789222',
    projectId: 'my-napo-pizza',
    authDomain: 'my-napo-pizza.firebaseapp.com',
    storageBucket: 'my-napo-pizza.appspot.com',
    measurementId: 'G-FVM4Q68QVJ',
  );

}